### ISSUE TITLE
Config module - Update only works merge

### ISSUE THREAD

**Issue by alexandregoncalves17** [ansible-collections/junipernetworks.junos#254] opened 2021-11-15 18:12 UTC
##### SUMMARY
In the field "update" only works "merge", if we try with other thing like "override", it give us an error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junipernetworks.junos.junos_config

##### ANSIBLE VERSION

```paste below
ansible-core: 2.12.0
```

##### COLLECTION VERSION

```paste below
Junipernetworks.junos: 2.6.0  

```

##### PLAYBOOK
```paste below
![Screenshot 2021-11-15 at 18 07 00](https://user-images.githubusercontent.com/78537912/141832659-490dca28-ef7e-4332-8c5c-1223c8e59847.png)

```

##### OS / ENVIRONMENT

Debian 10

##### RESULTS
```paste below

![Screenshot 2021-11-15 at 18 07 27](https://user-images.githubusercontent.com/78537912/141832620-74799a91-a43b-41f4-ab62-e74d0a8e5fdd.png)
```

**Comment by rohitthakur2590** [comment] 2021-12-21 06:58
This could be a problem with formed task content, could you please share the detailed output of the above tasks.
To get detailed logs you can perform these steps:
```
export ANSIBLE_LOG_PATH=detailed_logs.log
export ANSIBLE_PERSISTENT_LOG_MESSAGES=TRUE
export ANSIBLE_DEBUG=TRUE
```
and then run the playbook with command
`ansible-playbook -vvvv yourplaybook.yaml`

**Comment by alexandregoncalves17** [comment] 2021-12-29 12:20
> @alexandregoncalves17 This could be a problem with formed task content, could you please share the detailed output of the above tasks. To get detailed logs you can perform these steps:
> 
> ```
> export ANSIBLE_LOG_PATH=detailed_logs.log
> export ANSIBLE_PERSISTENT_LOG_MESSAGES=TRUE
> export ANSIBLE_DEBUG=TRUE
> ```
> 
> and then run the playbook with command `ansible-playbook -vvvv yourplaybook.yaml`
[override.txt](https://github.com/ansible-collections/junipernetworks.junos/files/7788797/override.txt)

Thanks for your reply!

**Comment by smarques-enxt** [comment] 2022-05-06 09:04
Also having the same issue guys... can you help please??

**Comment by rohitthakur2590** [comment] 2022-05-09 06:50
@alexandregoncalves17  :  going through logs 
```
ansible.module_utils.connection.ConnectionError: b"error: Missing mandatory statement: 'root-authentication'\nerror: configuration check-out failed: (missing mandatory statements)"
```
this could be be something resolved with configuring root user password. 
if this issue is still consistent, we could know more about the scenario with the exact cli commands you have been executing on Junos box.

**Comment by alexandregoncalves17** [comment] 2022-05-09 08:46
@rohitthakur2590 Hello, thanks for your answer! 

Already tried with the root configurations, but keeps giving me the same error.

I'm trying to import a jinja2 template with the override mode.

**Comment by rohitthakur2590** [comment] 2022-11-17 06:49
@alexandregoncalves17  is this issue still persist, If root cause was not root authentication, this could be due to some incomplete or inconsistent configuration. The error is something we are getting from network device.

If you still seeing this issue, Please open a new issue if possible with the configuration.

**Closed by rohitthakur2590** 2022-11-17 06:49 UTC
Labels: needs_info
