### ISSUE TITLE
junos_facts module doesnt gather all hardware modules.

### ISSUE THREAD

**Issue by roadracer96** [ansible-collections/junipernetworks.junos#328] opened 2022-09-28 14:50 UTC
##### SUMMARY
Only "top level" chassis components are gathered.  The output of "show chassis hardware" is hierarchical, specifically in the context of line cards and optics.  FPC X -> MIC Y -> PIC Z -> Xcvr N.  The module only collects information about FPC X and discards the rest.  Example:
FPC 3            REV 23   750-045372   CAFK6055          MPCE Type 3 3D
  CPU            REV 11   711-035209   CAFT7106          HMPC PMB 2G 
  MIC 0          REV 20   750-033199   CACX2503          1X100GE CFP
    PIC 0                 BUILTIN      BUILTIN           1X100GE CFP
      Xcvr 0     REV 01   740-047682   J16G34981         CFP-100G-LR4
  MIC 1          REV 09   750-036233   CACN1735          2X40GE QSFPP
    PIC 2                 BUILTIN      BUILTIN           2X40GE QSFPP
      Xcvr 1     REV 0    740-038624   F171JU13483-2     QSFP+-40G-CU3M

Subset of XML:           <chassis-module>            
                <name>FPC 3</name>
                <version>REV 23</version>
                <part-number>750-045372</part-number>
                <serial-number>CAFK6055</serial-number>
                <description>MPCE Type 3 3D</description>
                <clei-code>COUIBBNBAC</clei-code>
                <model-number>MX-MPC3E-3D</model-number>
                <chassis-sub-module>
                    <name>CPU</name>
                    <version>REV 11</version>
                    <part-number>711-035209</part-number>
                    <serial-number>CAFT7106</serial-number>
                    <description>HMPC PMB 2G </description>
                </chassis-sub-module>
                <chassis-sub-module>
                    <name>MIC 0</name>
                    <version>REV 20</version>
                    <part-number>750-033199</part-number>
                    <serial-number>CACX2503</serial-number>
                    <description>1X100GE CFP</description>
                    <clei-code>COUIBA8BAA</clei-code>
                    <model-number>MIC3-3D-1X100GE-CFP</model-number>
                    <chassis-sub-sub-module>
                        <name>PIC 0</name>
                        <part-number>BUILTIN</part-number>
                        <serial-number>BUILTIN</serial-number>
                        <description>1X100GE CFP</description>
                        <chassis-sub-sub-sub-module>
                            <name>Xcvr 0</name>
                            <version>REV 01</version>
                            <part-number>740-047682</part-number>
                            <serial-number>J16G34981</serial-number>
                            <description>CFP-100G-LR4</description>
                        </chassis-sub-sub-sub-module>
                    </chassis-sub-sub-module>
                </chassis-sub-module>
                <chassis-sub-module>
                    <name>MIC 1</name>
                    <version>REV 09</version>
                    <part-number>750-036233</part-number>
                    <serial-number>CACN1735</serial-number>
                    <description>2X40GE QSFPP</description>
                    <clei-code>IPUCA9ZCAA</clei-code>
                    <model-number>MIC3-3D-2X40GE-QSFPP</model-number>
                    <chassis-sub-sub-module>
                        <name>PIC 2</name>
                        <part-number>BUILTIN</part-number>
                        <serial-number>BUILTIN</serial-number>
                        <description>2X40GE QSFPP</description>
                        <chassis-sub-sub-sub-module>
                            <name>Xcvr 1</name>
                            <version>REV 0</version>
                            <part-number>740-038624</part-number>
                            <serial-number>F171JU13483-2</serial-number>
                            <description>QSFP+-40G-CU3M</description>
                        </chassis-sub-sub-sub-module>
                    </chassis-sub-sub-module>
                </chassis-sub-module>
            </chassis-module>

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junos_facts

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/MERIT/denike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/MERIT/denike/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True

```

##### COLLECTION VERSION

```paste below
# /usr/lib/python3/dist-packages/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 2.10.0 

# /home/MERIT/denike/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 3.1.0  

```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 10
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/opt/ansible/netdevices']
DEFAULT_MODULE_NAME(/etc/ansible/ansible.cfg) = raw
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_legacy_silent
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 60
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

Simply use the junos_facts module

```yaml
---
- name: Get JunOS Facts
  junipernetworks.junos.junos_facts:
    gather_subset: [ hardware,interfaces ]
    gather_network_resources: [ lacp,lacp_interfaces,lag_interfaces,l2_interfaces,l3_interfaces,interfaces ]
  register: facts

```

##### EXPECTED RESULTS
Expected to see all hardware information in order to gather inventory of field serviceable components all the way down to the optical transceiver level.

##### ACTUAL RESULTS
Only top level hardware components are exposed.

```paste below
- description: MPC Type 2 3D
  model: MX-MPC2-3D
  name: FPC 5
  part: 750-031089
  serial: ABBL3702

```

**Comment by elchico2007** [comment] 2022-11-14 20:24
@roadracer96 Can you share a screenshot of what you see from the device CLI?

**Comment by roadracer96** [comment] 2022-11-15 15:14
The module picks out the chassis-module from the XML, but not the chassis-sub-module or chassis-sub-sub-module or the chassis-sub-sub-sub-module.  We should be returning all data right down to the type of optic in a plug-able port.  Sorry about the XML.. It doesnt display very well if I dont do the quoting and that makes it not display very well either.. 

**Ansible verbose output:**
        "ansible_net_modules": [
            {
                "description": "MX480 Midplane",
                "model_number": "CHAS-BP-MX480-S",
                "name": "Midplane",
                "part_number": "710-017414",
                "serial_number": "TR3128",
                "version": "REV 05"
            },
            {
                "description": "Front Panel Display",
                "model_number": "CRAFT-MX480-S",
                "name": "FPM Board",
                "part_number": "710-017254",
                "serial_number": "KE1631",
                "version": "REV 02"
            },
            {
                "description": "PS 1.4-2.52kW; 90-264V AC in",
                "model_number": "PWR-MX480-2520-AC-S",
                "name": "PEM 0",
                "part_number": "740-029970",
                "serial_number": "QCS1601U04F",
                "version": "Rev 11"
            },
            {
                "description": "PS 1.4-2.52kW; 90-264V AC in",
                "model_number": "PWR-MX480-2520-AC-S",
                "name": "PEM 1",
                "part_number": "740-029970",
                "serial_number": "QCS1601U04P",
                "version": "Rev 11"
            },
            {
                "description": "PS 1.4-2.52kW; 90-264V AC in",
                "model_number": "PWR-MX480-2520-AC-S",
                "name": "PEM 2",
                "part_number": "740-029970",
                "serial_number": "QCS1601U0AF",
                "version": "Rev 11"
            },
            {
                "description": "PS 1.4-2.52kW; 90-264V AC in",
                "model_number": "PWR-MX480-2520-AC-S",
                "name": "PEM 3",
                "part_number": "740-029970",
                "serial_number": "QCS1601U00P",
                "version": "Rev 11"
            },
            {
                "clei_code": "COUCASKBAA",
                "description": "RE-S-1800x4",
                "model_number": "RE-S-1800X4-16G-S",
                "name": "Routing Engine 0",
                "part_number": "740-031116",
                "serial_number": "9009158058",
                "version": "REV 08"
            },
            {
                "clei_code": "COUCASYBAA",
                "description": "RE-S-1800x4",
                "model_number": "RE-S-1800X4-16G-S",
                "name": "Routing Engine 1",
                "part_number": "740-031116",
                "serial_number": "9009211349",
                "version": "REV 10"
            },
            {
                "clei_code": "COUCATYBAA",
                "description": "Enhanced MX SCB 2",
                "model_number": "SCBE2-MX-S",
                "name": "CB 0",
                "part_number": "750-055976",
                "serial_number": "CAFA9891",
                "version": "REV 05"
            },
            {
                "clei_code": "COUCATYBAA",
                "description": "Enhanced MX SCB 2",
                "model_number": "SCBE2-MX-S",
                "name": "CB 1",
                "part_number": "750-055976",
                "serial_number": "CAFA9633",
                "version": "REV 05"
            },
            {
                "chassis_sub_module": null,
                "description": "MPC 3D 16x 10GE",
                "model_number": "MPC-3D-16XGE-SFPP",
                "name": "FPC 2",
                "part_number": "750-028467",
                "serial_number": "ABBS0202",
                "version": "REV 38"
            },
            {
                "chassis_sub_module": null,
                "clei_code": "COUIBBNBAB",
                "description": "MPCE Type 3 3D",
                "model_number": "MX-MPC3E-3D",
                "name": "FPC 3",
                "part_number": "750-045372",
                "serial_number": "CACY0564",
                "version": "REV 14"
            },
            {
                "description": "Enhanced Left Fan Tray",
                "model_number": "FFANTRAY-MX480-HC-S",
                "name": "Fan Tray"
            }
        ],


**CLI Output:**
Hardware inventory:
Item             Version  Part number  Serial number     Description
Chassis                                JN10FF555AFB      MX480
Midplane         REV 05   710-017414   TR3128            MX480 Midplane
FPM Board        REV 02   710-017254   KE1631            Front Panel Display
PEM 0            Rev 11   740-029970   QCS1601U04F       PS 1.4-2.52kW; 90-264V AC in
PEM 1            Rev 11   740-029970   QCS1601U04P       PS 1.4-2.52kW; 90-264V AC in
PEM 2            Rev 11   740-029970   QCS1601U0AF       PS 1.4-2.52kW; 90-264V AC in
PEM 3            Rev 11   740-029970   QCS1601U00P       PS 1.4-2.52kW; 90-264V AC in
Routing Engine 0 REV 08   740-031116   9009158058        RE-S-1800x4
Routing Engine 1 REV 10   740-031116   9009211349        RE-S-1800x4
CB 0             REV 05   750-055976   CAFA9891          Enhanced MX SCB 2
CB 1             REV 05   750-055976   CAFA9633          Enhanced MX SCB 2
FPC 2            REV 38   750-028467   ABBS0202          MPC 3D 16x 10GE
  CPU            REV 12   711-029089   ABBR3454          AMPC PMB
  PIC 0                   BUILTIN      BUILTIN           4x 10GE(LAN) SFP+
    Xcvr 0       REV 01   740-031981   F179JU01240       SFP+-10G-LR
    Xcvr 1       REV 01   740-031981   F179JU01254       SFP+-10G-LR
    Xcvr 2       REV 01   740-031981   F179JU01237       SFP+-10G-LR
    Xcvr 3       REV 01   740-031981   F179JU01257       SFP+-10G-LR
  PIC 1                   BUILTIN      BUILTIN           4x 10GE(LAN) SFP+
    Xcvr 0       REV 01   740-021309   FS40311M0029      SFP+-10G-LR
    Xcvr 1       REV 01   740-021309   C1807080221       SFP+-10G-LR
  PIC 2                   BUILTIN      BUILTIN           4x 10GE(LAN) SFP+
    Xcvr 0       REV 01   740-030077   JNS21I60298       SFP+-10G-CU3M
    Xcvr 1       REV 01   740-030077   JNS21I60298       SFP+-10G-CU3M
  PIC 3                   BUILTIN      BUILTIN           4x 10GE(LAN) SFP+
FPC 3            REV 14   750-045372   CACY0564          MPCE Type 3 3D
  CPU            REV 10   711-035209   CACY9250          HMPC PMB 2G 
  MIC 0          REV 12   750-033307   CAGP6185          10X10GE SFPP
    PIC 0                 BUILTIN      BUILTIN           10X10GE SFPP
      Xcvr 0     REV 01   740-031980   M0708040319       SFP+-10G-SR
      Xcvr 1     REV 01   740-031980   M0708040292       SFP+-10G-SR
      Xcvr 2     REV 01   740-031980   M0708040312       SFP+-10G-SR
      Xcvr 3     REV 01   740-031980   M0708040295       SFP+-10G-SR
      Xcvr 4     REV 01   740-021309   FS40311M0028      SFP+-10G-LR
      Xcvr 5     REV 01   740-030077   JNS21I60298       SFP+-10G-CU3M
      Xcvr 6     REV 01   740-030077   JNS21I60298       SFP+-10G-CU3M
      Xcvr 9     ''       NON-JNPR     FS41111M0091      SFP+-10G-LR
  MIC 1          REV 12   750-036233   CAEZ4606          2X40GE QSFPP
    PIC 2                 BUILTIN      BUILTIN           2X40GE QSFPP
      Xcvr 0     REV 01   740-043308   F177JU05515       QSFP+-40G-LR4
      Xcvr 1     REV 01   740-043308   F177JU05514       QSFP+-40G-LR4
Fan Tray                                                 Enhanced Left Fan Tray

**CLI XML Output:**

[junos_hardware_output.txt](https://github.com/ansible-collections/junipernetworks.junos/files/10013842/junos_hardware_output.txt)

`
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/20.2R0/junos">
    <chassis-inventory xmlns="http://xml.juniper.net/junos/20.2R0/junos-chassis">
        <chassis junos:style="inventory">
            <name>Chassis</name>
            <serial-number>JN10FF555AFB</serial-number>
            <description>MX480</description>
            <chassis-module>
                <name>Midplane</name>
                <version>REV 05</version>
                <part-number>710-017414</part-number>
                <serial-number>TR3128</serial-number>
                <description>MX480 Midplane</description>
                <model-number>CHAS-BP-MX480-S</model-number>
            </chassis-module>
            <chassis-module>
                <name>FPM Board</name>
                <version>REV 02</version>
                <part-number>710-017254</part-number>
                <serial-number>KE1631</serial-number>
                <description>Front Panel Display</description>
                <model-number>CRAFT-MX480-S</model-number>
            </chassis-module>
            <chassis-module>
                <name>PEM 0</name>
                <version>Rev 11</version>
                <part-number>740-029970</part-number>
                <serial-number>QCS1601U04F</serial-number>
                <description>PS 1.4-2.52kW; 90-264V AC in</description>
                <model-number>PWR-MX480-2520-AC-S</model-number>
            </chassis-module>
            <chassis-module>
                <name>PEM 1</name>
                <version>Rev 11</version>
                <part-number>740-029970</part-number>
                <serial-number>QCS1601U04P</serial-number>
                <description>PS 1.4-2.52kW; 90-264V AC in</description>
                <model-number>PWR-MX480-2520-AC-S</model-number>
            </chassis-module>
            <chassis-module>
                <name>PEM 2</name>
                <version>Rev 11</version>
                <part-number>740-029970</part-number>
                <serial-number>QCS1601U0AF</serial-number>
                <description>PS 1.4-2.52kW; 90-264V AC in</description>
                <model-number>PWR-MX480-2520-AC-S</model-number>
            </chassis-module>
            <chassis-module>
                <name>PEM 3</name>      
                <version>Rev 11</version>
                <part-number>740-029970</part-number>
                <serial-number>QCS1601U00P</serial-number>
                <description>PS 1.4-2.52kW; 90-264V AC in</description>
                <model-number>PWR-MX480-2520-AC-S</model-number>
            </chassis-module>
            <chassis-module>
                <name>Routing Engine 0</name>
                <version>REV 08</version>
                <part-number>740-031116</part-number>
                <serial-number>9009158058</serial-number>
                <description>RE-S-1800x4</description>
                <clei-code>COUCASKBAA</clei-code>
                <model-number>RE-S-1800X4-16G-S</model-number>
            </chassis-module>
            <chassis-module>
                <name>Routing Engine 1</name>
                <version>REV 10</version>
                <part-number>740-031116</part-number>
                <serial-number>9009211349</serial-number>
                <description>RE-S-1800x4</description>
                <clei-code>COUCASYBAA</clei-code>
                <model-number>RE-S-1800X4-16G-S</model-number>
            </chassis-module>
            <chassis-module>
                <name>CB 0</name>
                <version>REV 05</version>
                <part-number>750-055976</part-number>
                <serial-number>CAFA9891</serial-number>
                <description>Enhanced MX SCB 2</description>
                <clei-code>COUCATYBAA</clei-code>
                <model-number>SCBE2-MX-S</model-number>
            </chassis-module>
            <chassis-module>
                <name>CB 1</name>
                <version>REV 05</version>
                <part-number>750-055976</part-number>
                <serial-number>CAFA9633</serial-number>
                <description>Enhanced MX SCB 2</description>
                <clei-code>COUCATYBAA</clei-code>
                <model-number>SCBE2-MX-S</model-number>
            </chassis-module>
            <chassis-module>
                <name>FPC 2</name>
                <version>REV 38</version>
                <part-number>750-028467</part-number>
                <serial-number>ABBS0202</serial-number>
                <description>MPC 3D 16x 10GE</description>
                <model-number>MPC-3D-16XGE-SFPP</model-number>
                <chassis-sub-module>
                    <name>CPU</name>
                    <version>REV 12</version>
                    <part-number>711-029089</part-number>
                    <serial-number>ABBR3454</serial-number>
                    <description>AMPC PMB</description>
                </chassis-sub-module>
                <chassis-sub-module>
                    <name>PIC 0</name>
                    <part-number>BUILTIN</part-number>
                    <serial-number>BUILTIN</serial-number>
                    <description>4x 10GE(LAN) SFP+</description>
                    <chassis-sub-sub-module>
                        <name>Xcvr 0</name>
                        <version>REV 01</version>
                        <part-number>740-031981</part-number>
                        <serial-number>F179JU01240</serial-number>
                        <description>SFP+-10G-LR</description>
                    </chassis-sub-sub-module>
                    <chassis-sub-sub-module>
                        <name>Xcvr 1</name>
                        <version>REV 01</version>
                        <part-number>740-031981</part-number>
                        <serial-number>F179JU01254</serial-number>
                        <description>SFP+-10G-LR</description>
                    </chassis-sub-sub-module>
                    <chassis-sub-sub-module>
                        <name>Xcvr 2</name>
                        <version>REV 01</version>
                        <part-number>740-031981</part-number>
                        <serial-number>F179JU01237</serial-number>
                        <description>SFP+-10G-LR</description>
                    </chassis-sub-sub-module>
                    <chassis-sub-sub-module>
                        <name>Xcvr 3</name>
                        <version>REV 01</version>
                        <part-number>740-031981</part-number>
                        <serial-number>F179JU01257</serial-number>
                        <description>SFP+-10G-LR</description>
                    </chassis-sub-sub-module>
                </chassis-sub-module>
                <chassis-sub-module>
                    <name>PIC 1</name>
                    <part-number>BUILTIN</part-number>
                    <serial-number>BUILTIN</serial-number>
                    <description>4x 10GE(LAN) SFP+</description>
                    <chassis-sub-sub-module>
                        <name>Xcvr 0</name>
                        <version>REV 01</version>
                        <part-number>740-021309</part-number>
                        <serial-number>FS40311M0029</serial-number>
                        <description>SFP+-10G-LR</description>
                    </chassis-sub-sub-module>
                    <chassis-sub-sub-module>
                        <name>Xcvr 1</name>
                        <version>REV 01</version>
                        <part-number>740-021309</part-number>
                        <serial-number>C1807080221</serial-number>
                        <description>SFP+-10G-LR</description>
                    </chassis-sub-sub-module>
                </chassis-sub-module>
                <chassis-sub-module>
                    <name>PIC 2</name>
                    <part-number>BUILTIN</part-number>
                    <serial-number>BUILTIN</serial-number>
                    <description>4x 10GE(LAN) SFP+</description>
                    <chassis-sub-sub-module>
                        <name>Xcvr 0</name>
                        <version>REV 01</version>
                        <part-number>740-030077</part-number>
                        <serial-number>JNS21I60298</serial-number>
                        <description>SFP+-10G-CU3M</description>
                    </chassis-sub-sub-module>
                    <chassis-sub-sub-module>
                        <name>Xcvr 1</name>
                        <version>REV 01</version>
                        <part-number>740-030077</part-number>
                        <serial-number>JNS21I60298</serial-number>
                        <description>SFP+-10G-CU3M</description>
                    </chassis-sub-sub-module>
                </chassis-sub-module>
                <chassis-sub-module>
                    <name>PIC 3</name>
                    <part-number>BUILTIN</part-number>
                    <serial-number>BUILTIN</serial-number>
                    <description>4x 10GE(LAN) SFP+</description>
                </chassis-sub-module>
            </chassis-module>
            <chassis-module>
                <name>FPC 3</name>
                <version>REV 14</version>
                <part-number>750-045372</part-number>
                <serial-number>CACY0564</serial-number>
                <description>MPCE Type 3 3D</description>
                <clei-code>COUIBBNBAB</clei-code>
                <model-number>MX-MPC3E-3D</model-number>
                <chassis-sub-module>
                    <name>CPU</name>
                    <version>REV 10</version>
                    <part-number>711-035209</part-number>
                    <serial-number>CACY9250</serial-number>
                    <description>HMPC PMB 2G </description>
                </chassis-sub-module>
                <chassis-sub-module>
                    <name>MIC 0</name>
                    <version>REV 12</version>
                    <part-number>750-033307</part-number>
                    <serial-number>CAGP6185</serial-number>
                    <description>10X10GE SFPP</description>
                    <clei-code>COUIBD8BAA</clei-code>
                    <model-number>MIC3-3D-10XGE-SFPP</model-number>
                    <chassis-sub-sub-module>
                        <name>PIC 0</name>
                        <part-number>BUILTIN</part-number>
                        <serial-number>BUILTIN</serial-number>
                        <description>10X10GE SFPP</description>
                        <chassis-sub-sub-sub-module>
                            <name>Xcvr 0</name>
                            <version>REV 01</version>
                            <part-number>740-031980</part-number>
                            <serial-number>M0708040319</serial-number>
                            <description>SFP+-10G-SR</description>
                        </chassis-sub-sub-sub-module>
                        <chassis-sub-sub-sub-module>
                            <name>Xcvr 1</name>
                            <version>REV 01</version>
                            <part-number>740-031980</part-number>
                            <serial-number>M0708040292</serial-number>
                            <description>SFP+-10G-SR</description>
                        </chassis-sub-sub-sub-module>
                        <chassis-sub-sub-sub-module>
                            <name>Xcvr 2</name>
                            <version>REV 01</version>
                            <part-number>740-031980</part-number>
                            <serial-number>M0708040312</serial-number>
                            <description>SFP+-10G-SR</description>
                        </chassis-sub-sub-sub-module>
                        <chassis-sub-sub-sub-module>
                            <name>Xcvr 3</name>
                            <version>REV 01</version>
                            <part-number>740-031980</part-number>
                            <serial-number>M0708040295</serial-number>
                            <description>SFP+-10G-SR</description>
                        </chassis-sub-sub-sub-module>
                        <chassis-sub-sub-sub-module>
                            <name>Xcvr 4</name>
                            <version>REV 01</version>
                            <part-number>740-021309</part-number>
                            <serial-number>FS40311M0028</serial-number>
                            <description>SFP+-10G-LR</description>
                        </chassis-sub-sub-sub-module>
                        <chassis-sub-sub-sub-module>
                            <name>Xcvr 5</name>
                            <version>REV 01</version>
                            <part-number>740-030077</part-number>
                            <serial-number>JNS21I60298</serial-number>
                            <description>SFP+-10G-CU3M</description>
                        </chassis-sub-sub-sub-module>
                        <chassis-sub-sub-sub-module>
                            <name>Xcvr 6</name>
                            <version>REV 01</version>
                            <part-number>740-030077</part-number>
                            <serial-number>JNS21I60298</serial-number>
                            <description>SFP+-10G-CU3M</description>
                        </chassis-sub-sub-sub-module>
                        <chassis-sub-sub-sub-module>
                            <name>Xcvr 9</name>
                            <version>''</version>
                            <part-number>NON-JNPR</part-number>
                            <serial-number>FS41111M0091</serial-number>
                            <description>SFP+-10G-LR</description>
                        </chassis-sub-sub-sub-module>
                    </chassis-sub-sub-module>
                </chassis-sub-module>
                <chassis-sub-module>
                    <name>MIC 1</name>
                    <version>REV 12</version>
                    <part-number>750-036233</part-number>
                    <serial-number>CAEZ4606</serial-number>
                    <description>2X40GE QSFPP</description>
                    <clei-code>IPUCBJECAA</clei-code>
                    <model-number>MIC3-3D-2X40GE-QSFPP</model-number>
                    <chassis-sub-sub-module>
                        <name>PIC 2</name>
                        <part-number>BUILTIN</part-number>
                        <serial-number>BUILTIN</serial-number>
                        <description>2X40GE QSFPP</description>
                        <chassis-sub-sub-sub-module>
                            <name>Xcvr 0</name>
                            <version>REV 01</version>
                            <part-number>740-043308</part-number>
                            <serial-number>F177JU05515</serial-number>
                            <description>QSFP+-40G-LR4</description>
                        </chassis-sub-sub-sub-module>
                        <chassis-sub-sub-sub-module>
                            <name>Xcvr 1</name>
                            <version>REV 01</version>
                            <part-number>740-043308</part-number>
                            <serial-number>F177JU05514</serial-number>
                            <description>QSFP+-40G-LR4</description>
                        </chassis-sub-sub-sub-module>
                    </chassis-sub-sub-module>
                </chassis-sub-module>
            </chassis-module>
            <chassis-module>
                <name>Fan Tray</name>
                <description>Enhanced Left Fan Tray</description>
                <model-number>FFANTRAY-MX480-HC-S</model-number>
            </chassis-module>
        </chassis>
    </chassis-inventory>
    <cli>
        <banner>{master}</banner>
    </cli>
</rpc-reply>
`

**Comment by elchico2007** [comment] 2022-11-15 18:20
Got it, what ansible connection are you using? network_cli or netconf?

**Comment by roadracer96** [comment] 2022-11-15 19:13
Netconf

The xml output provided is from the CLI, which is exactly what netconf will
give you.

**Comment by elchico2007** [comment] 2022-11-15 19:53
@roadracer96 got it, this is what i manage to get from the changes i made, let me know if it gathered everything from what you expected to see.
`"ansible_net_modules": [
            {
                "description": "MX480 Midplane",
                "model_number": "CHAS-BP-MX480-S",
                "name": "Midplane",
                "part_number": "710-017414",
                "serial_number": "TR3128",
                "version": "REV 05"
            },
            {
                "description": "Front Panel Display",
                "model_number": "CRAFT-MX480-S",
                "name": "FPM Board",
                "part_number": "710-017254",
                "serial_number": "KE1631",
                "version": "REV 02"
            },
            {
                "description": "PS 1.4-2.52kW; 90-264V AC in",
                "model_number": "PWR-MX480-2520-AC-S",
                "name": "PEM 0",
                "part_number": "740-029970",
                "serial_number": "QCS1601U04F",
                "version": "Rev 11"
            },
            {
                "description": "PS 1.4-2.52kW; 90-264V AC in",
                "model_number": "PWR-MX480-2520-AC-S",
                "name": "PEM 1",
                "part_number": "740-029970",
                "serial_number": "QCS1601U04P",
                "version": "Rev 11"
            },
            {
                "description": "PS 1.4-2.52kW; 90-264V AC in",
                "model_number": "PWR-MX480-2520-AC-S",
                "name": "PEM 2",
                "part_number": "740-029970",
                "serial_number": "QCS1601U0AF",
                "version": "Rev 11"
            },
            {
                "description": "PS 1.4-2.52kW; 90-264V AC in",
                "model_number": "PWR-MX480-2520-AC-S",
                "name": "PEM 3",
                "part_number": "740-029970",
                "serial_number": "QCS1601U00P",
                "version": "Rev 11"
            },
            {
                "clei_code": "COUCASKBAA",
                "description": "RE-S-1800x4",
                "model_number": "RE-S-1800X4-16G-S",
                "name": "Routing Engine 0",
                "part_number": "740-031116",
                "serial_number": "9009158058",
                "version": "REV 08"
            },
            {
                "clei_code": "COUCASYBAA",
                "description": "RE-S-1800x4",
                "model_number": "RE-S-1800X4-16G-S",
                "name": "Routing Engine 1",
                "part_number": "740-031116",
                "serial_number": "9009211349",
                "version": "REV 10"
            },
            {
                "clei_code": "COUCATYBAA",
                "description": "Enhanced MX SCB 2",
                "model_number": "SCBE2-MX-S",
                "name": "CB 0",
                "part_number": "750-055976",
                "serial_number": "CAFA9891",
                "version": "REV 05"
            },
            {
                "clei_code": "COUCATYBAA",
                "description": "Enhanced MX SCB 2",
                "model_number": "SCBE2-MX-S",
                "name": "CB 1",
                "part_number": "750-055976",
                "serial_number": "CAFA9633",
                "version": "REV 05"
            },
            {
                "chassis_sub_module": {
                    "chassis-sub-module": {
                        "description": "4x 10GE(LAN) SFP+",
                        "name": "PIC 3",
                        "part-number": "BUILTIN",
                        "serial-number": "BUILTIN"
                    }
                },
                "description": "MPC 3D 16x 10GE",
                "model_number": "MPC-3D-16XGE-SFPP",
                "name": "FPC 2",
                "part_number": "750-028467",
                "serial_number": "ABBS0202",
                "version": "REV 38"
            },
            {
                "chassis_sub_module": {
                    "chassis-sub-module": {
                        "chassis-sub-sub-module": {
                            "chassis-sub-sub-sub-module": [
                                {
                                    "description": "QSFP+-40G-LR4",
                                    "name": "Xcvr 0",
                                    "part-number": "740-043308",
                                    "serial-number": "F177JU05515",
                                    "version": "REV 01"
                                },
                                {
                                    "description": "QSFP+-40G-LR4",
                                    "name": "Xcvr 1",
                                    "part-number": "740-043308",
                                    "serial-number": "F177JU05514",
                                    "version": "REV 01"
                                }
                            ],
                            "description": "2X40GE QSFPP",
                            "name": "PIC 2",
                            "part-number": "BUILTIN",
                            "serial-number": "BUILTIN"
                        },
                        "clei-code": "IPUCBJECAA",
                        "description": "2X40GE QSFPP",
                        "model-number": "MIC3-3D-2X40GE-QSFPP",
                        "name": "MIC 1",
                        "part-number": "750-036233",
                        "serial-number": "CAEZ4606",
                        "version": "REV 12"
                    }
                },
                "clei_code": "COUIBBNBAB",
                "description": "MPCE Type 3 3D",
                "model_number": "MX-MPC3E-3D",
                "name": "FPC 3",
                "part_number": "750-045372",
                "serial_number": "CACY0564",
                "version": "REV 14"
            },
            {
                "description": "Enhanced Left Fan Tray",
                "model_number": "FFANTRAY-MX480-HC-S",
                "name": "Fan Tray"
            }
        ],`

**Comment by rohitthakur2590** [comment] 2022-11-17 09:51
@roadracer96  Thanks for reporting this, this seems to be a legit issue.root cause of this seems to be not expecting 'chassis-sub-module' list. It will be fixed in upcoming release.

**Comment by roadracer96** [comment] 2022-11-17 13:19
Thanks!  LMK when this is available pre-release.  I have an immediate use for it that will save me a lot of time!

**Comment by elchico2007** [comment] 2022-11-17 14:06
@rohitthakur2590 I have the fix on a fork that i made from the repo, how can i issue a pull request back into the main repo?

**Closed** 2022-11-30 11:16 UTC
Labels: bug, has_pr
